/**
 * Terms of Service and Privacy Policy.
 *
 * Specific rather than boilerplate, because the two things this product does
 * that generic SaaS terms do not cover are the two that matter most: it
 * records phone calls between a customer's business and that business's own
 * customers, and it sends that audio to a third-party AI model. Both are
 * named here explicitly, along with every sub-processor the data passes
 * through.
 *
 * Written as a starting point a lawyer should review before the product takes
 * paying customers — not as a substitute for one.
 */
import React from 'react';
import {Link} from 'react-router-dom';
import {MarketingShell} from './marketing';

const UPDATED = '9 October 2026';

function LegalPage({title, children}: {title: string; children: React.ReactNode}) {
  return <MarketingShell>
    <main>
      <section className="m-page-hero m-legal-hero">
        <div className="m-container">
          <div className="m-kicker">LEGAL</div>
          <h1>{title}</h1>
          <p>Last updated {UPDATED}.</p>
        </div>
      </section>
      <section className="m-section">
        <div className="m-container m-legal">{children}</div>
      </section>
    </main>
  </MarketingShell>;
}

export function TermsPage() {
  return <LegalPage title="Terms of Service">
    <p>These terms govern use of Calling Agent (the &ldquo;Service&rdquo;), which answers phone calls and WhatsApp
      conversations for a business using an AI agent, with a human able to take over at any time. By creating a
      workspace or using the Service, you agree to these terms on behalf of the business you represent
      (&ldquo;you&rdquo;).</p>

    <h2>1. What the Service does</h2>
    <p>The Service connects to a phone number and/or WhatsApp Business number you control, places and receives calls
      and messages on it, and answers using an AI agent configured with your own greeting, persona and knowledge base.
      A member of your team can listen in, take over a live call, or hand it back to the agent.</p>

    <h2>2. Your account and credentials</h2>
    <p>You are responsible for the accuracy of the carrier, WhatsApp and Google credentials you connect, for keeping
      your API key confidential, and for everything done through your workspace. Tell us immediately if you believe a
      credential or key has been exposed, so it can be rotated.</p>

    <h2>3. Recording and consent</h2>
    <p>When you enable call recording, the Service records both sides of a call and stores the audio and transcript.
      <strong> You, not Calling Agent, are the party placing and receiving these calls.</strong> You are responsible
      for complying with the recording-consent, disclosure and data-protection laws of every place you operate and
      every place your callers are located, including two-party consent requirements where they apply. The Service can
      play a spoken disclosure at the start of a call if you configure one; whether that satisfies your jurisdiction is
      your determination to make, not ours.</p>

    <h2>4. AI-generated replies</h2>
    <p>The agent's replies are generated by a large language model from the knowledge base and persona you supply. It
      can be wrong. You are responsible for reviewing what your agent tells people, for the accuracy of the knowledge
      you upload, and for the consequences of an answer it gives. Do not configure the Service to give medical, legal,
      financial or safety-critical advice without a human reviewing it.</p>

    <h2>5. WhatsApp messaging</h2>
    <p>Outbound WhatsApp messages are subject to Meta's own policies: a free-text message only reaches someone inside
      the 24-hour customer-service window, and a first contact must use a template Meta has approved. You are
      responsible for the content of your templates and for only messaging people you have a lawful basis to
      contact.</p>

    <h2>6. Outbound calling campaigns</h2>
    <p>The campaigns feature places real calls, one at a time, to a list you provide. You are responsible for the
      legality of calling every number on that list, including do-not-call registers, permitted calling hours, and any
      requirement to identify your business at the start of a call. The Service will not automatically redial someone
      who did not answer; calling them again is a decision you make deliberately.</p>

    <h2>7. Acceptable use</h2>
    <p>You will not use the Service to place calls or send messages you have no lawful basis to send; to harass,
      defraud or deceive anyone about who is calling; to impersonate a person or organisation; or to circumvent the
      rate limits and security controls that protect the Service. We may suspend a workspace we reasonably believe is
      doing any of these, and will tell you why.</p>

    <h2>8. Availability</h2>
    <p>The Service is provided without a guaranteed uptime commitment while it is in active development. An outage at
      a provider the Service depends on — Meta, Infobip, Google or Supabase — can interrupt calling or messaging, and
      we are not liable for the consequences of an outage outside our own infrastructure.</p>

    <h2>9. Fees</h2>
    <p>Pricing and billing terms are agreed with you directly before they apply to your workspace. Nothing in these
      terms obligates you to a fee that has not been separately agreed in writing.</p>

    <h2>10. Your data</h2>
    <p>Your call logs, transcripts, recordings, messages, knowledge base and campaign lists belong to you. You can
      export your call and usage records from the dashboard, and may ask us at any time for a full export or for your
      workspace's data to be deleted.</p>

    <h2>11. Termination</h2>
    <p>You may stop using the Service and ask for your data to be deleted at any time. We may suspend or terminate a
      workspace that breaches section 7, with notice where practical.</p>

    <h2>12. Liability</h2>
    <p>The Service is provided &ldquo;as is.&rdquo; To the extent permitted by law, neither party is liable to the
      other for indirect, incidental or consequential damages arising from use of the Service.</p>

    <h2>13. Changes</h2>
    <p>The date at the top of this page changes when these terms do. We will tell you directly before a change that
      materially reduces your rights.</p>

    <h2>14. Contact</h2>
    <p>Questions about these terms can be sent through the <Link to="/contact">contact page</Link>.</p>
  </LegalPage>;
}

export function PrivacyPage() {
  return <LegalPage title="Privacy Policy">
    <p>This policy describes what Calling Agent collects, why, and who it is shared with. It is written for the
      business that operates a workspace (&ldquo;you&rdquo;). Where it affects the people who call or message your
      business, it also says what you need to tell them yourself.</p>

    <h2>1. What we collect</h2>
    <ul>
      <li><strong>Call and message content</strong> — audio recordings (when you enable recording), transcripts, and
        WhatsApp message text, on the numbers you connect.</li>
      <li><strong>Contact details</strong> — the phone numbers of people who call, message, or are called by your
        workspace, and any name attached to them in your campaign lists.</li>
      <li><strong>Configuration</strong> — your agent's persona, greeting, knowledge base documents and campaign
        lists.</li>
      <li><strong>Credentials</strong> — your WhatsApp, Infobip and Google connection details, encrypted at rest with
        AES-256-GCM and never displayed back in full to anyone, including you.</li>
      <li><strong>Usage data</strong> — call counts, minutes, message counts and similar aggregates, shown on your
        usage dashboard.</li>
    </ul>

    <h2>2. Why we collect it</h2>
    <p>To operate the agent on your calls and messages; to let your team review, search and take over conversations;
      to compute the usage figures you see; and to surface questions your agent could not answer, so you can improve
      your knowledge base.</p>

    <h2>3. Who it is shared with</h2>
    <p>We do not sell your data. It passes through the following sub-processors, each only as far as carrying a call or
      a message requires:</p>
    <ul>
      <li><strong>Meta (WhatsApp Business Platform)</strong> — to send and receive WhatsApp messages and calls on your
        number.</li>
      <li><strong>Infobip</strong> — to place and receive phone calls on your carrier number.</li>
      <li><strong>Google (Gemini API)</strong> — call audio and message text are sent to Gemini to generate the
        agent's spoken and written replies.</li>
      <li><strong>Google Drive</strong> — if you connect it, recordings are stored in a folder in your own Drive, under
        your own account rather than ours.</li>
      <li><strong>Supabase</strong> — our database provider, hosting your call logs, transcripts, knowledge base and
        configuration.</li>
    </ul>

    <h2>4. Retention</h2>
    <p>Call logs, transcripts and messages are kept until you delete them or close your workspace. You can delete an
      individual call's recording and transcript from its detail screen at any time.</p>

    <h2>5. Security</h2>
    <p>Credentials are encrypted at rest and never written to logs in full. Reaching your workspace's data requires
      your API key, and no request can read another workspace's data by changing a URL or a parameter — the workspace
      is derived from the key itself. Recordings are served through short-lived signed links rather than public
      URLs.</p>

    <h2>6. What you must tell the people you call</h2>
    <p>The people your workspace calls or messages are your customers, not ours. You are responsible for telling them,
      in whatever form your jurisdiction requires, that a call may be recorded and that they may be speaking with an
      AI agent. This policy covers our handling of their data on your behalf; it does not replace that
      disclosure.</p>

    <h2>7. Requests about personal data</h2>
    <p>If someone asks your business to delete their call history or messages, you can do it from your dashboard, or
      ask us to do it on your behalf through the <Link to="/contact">contact page</Link>.</p>

    <h2>8. International processing</h2>
    <p>The sub-processors above operate infrastructure in several countries. Using the Service means accepting that
      your data is processed in the countries where those providers operate.</p>

    <h2>9. Changes</h2>
    <p>The date at the top of this page changes when this policy does. We will tell you directly before a change that
      materially affects how your data is handled.</p>

    <h2>10. Contact</h2>
    <p>Questions about this policy, or a request to access, export or delete data, can be sent through the{' '}
      <Link to="/contact">contact page</Link>.</p>
  </LegalPage>;
}
