import React from 'react';
import {createRoot} from 'react-dom/client';
import App from './app';
import './style.css';
import './marketing.css';
import './workspace.css';
import './ai-theme.css';
import './polish.css';
import './motion.css';
import './layout.css';
import './chat.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
